# NumPy is a core Python library for scientific computing and data analysis.


*   Numpy provides fast, efficient n-dimensional arrays (ndarray) and a wide range of mathematical functions for operations like algebra, statistics, and transformations.
*  NumPy arrays are highly optimized for performance, making them essential in machine learning, data science, and scientific research.




### Creation of Numpy Arrays

In [ ]:
import numpy as np

In [ ]:
# Creation of ND arrays using array method.

In [ ]:
# 1 Dimensional.
arr1 = np.array([1,2,3,4])
print(arr1,type(arr1))

[1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
# 2 Dimensional
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3 Dimensional
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# 4 Dimensional
arr4 = np.array([[[[1,2],[3,4]],[[4,5],[6,7]]]])
print(arr4)

[[[[1 2]
   [3 4]]

  [[4 5]
   [6 7]]]]


In [ ]:
# 5 Dimensional

arr5 = np.array([[[[[1,2],[3,4]],[[5,6],[7,8]]]]])
print(arr5)

[[[[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]]]


In [ ]:
# Creation of ND arrays using zeros and ones method.

In [ ]:
arr_zeros = np.zeros((2,3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr_ones = np.ones((3,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Creation of ND arrays using Identity

In [ ]:
arr_identity = np.identity((5))
print(arr_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Creation of ND arrays using arange method

In [ ]:
arr_arange = np.arange(10)
print(arr_arange)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_aranges = np.arange(1,14)
print(arr_aranges)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


In [ ]:
# Creation of ND arrays using lin space method

In [ ]:
arr_space = np.linspace(10,30,10)
print(arr_space)

[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]


In [ ]:
arr_spaces = np.linspace(10,47,17)
print(arr_spaces)

[10.     12.3125 14.625  16.9375 19.25   21.5625 23.875  26.1875 28.5
 30.8125 33.125  35.4375 37.75   40.0625 42.375  44.6875 47.    ]


In [ ]:
# Creation of ND arrays using lin space method

In [ ]:
arr_copy = arr3.copy()
print(arr_copy)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Numpy Attributes

In [ ]:
# Ndim - It return the number of dimension of an ndarray.

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr_identity.ndim)
print(arr_spaces.ndim)

1
2
3
2
1


In [ ]:
# Shape - Determines the number of rows and columns that an ndarray is equipped.

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)
print(arr5.shape)
print(arr_identity.shape)

(4,)
(2, 3)
(2, 2, 2)
(1, 2, 2, 2)
(1, 1, 2, 2, 2)
(5, 5)


In [ ]:
# Size - Defines the number of item present in a ndarray.

print(arr1.size)
print(arr2.size)
print(arr3.size)
print(arr_space.size)

4
6
8
10


In [ ]:
# Itemsize - Returns the number bytes of each element of an nd array occupies in memory.

print(arr1.itemsize)
print(arr3.itemsize)
print(arr_identity.itemsize)
print(arr_spaces.itemsize)

8
8
8
8


In [ ]:
# Dtype - determines the data type of an element of an ndarray.

print(arr1.dtype)
print(arr3.dtype)
print(arr_identity.dtype)
print(arr_spaces.dtype)

int64
int64
float64
float64


In [ ]:
# Astype - A method which changes a data type to another.

print(arr4.dtype)
arr4_new = arr4.astype('float')
arr_identity_new = arr_identity.astype('int32')
print(arr_identity_new.dtype)
print(arr4_new.dtype)

int64
int32
float64
